config/routes.rb
require 'api_constraints'
Rails.application.routes.draw do
  mount Knock::Engine => '/knock'

  root 'home#index'
  get    'home'    => 'home#index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :apps
  resources :users
  resources :hello

  namespace :api, defaults: {format: "json"} do
    scope module: :v1 do


      resources :events do
        resources :tags, only: [:index, :create]
      end
      resources :tags, only: [:index, :show] do
        resources :events, only: [:index]
      end
      resources :positions, only: [:index, :show] do
        resources :events, only: [:index]
      end
      resources :creators, only: [:index, :show] do
        resources :events, only: [:index]
      end
    end
  end
end

app/models/app.rb
class App < ActiveRecord::Base

  before_create :generate_api_key
  belongs_to :user
  validates :name, presence: true,
            length: { maximum: 100}

  private


  def generate_api_key
    begin
      self.apikey = SecureRandom.hex
    end while self.class.exists?(apikey: apikey)
  end
end

app/models/creator.rb
class Creator < ActiveRecord::Base
  has_many :events
  has_secure_password
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :tags
  belongs_to :creator
  belongs_to :position

  validates :name, presence: true
  validates :description, presence: true


end

app/models/position.rb
class Position < ActiveRecord::Base
  has_one :event

  #validates :longitude, presence: true
  #validates :latitude, presence: true
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode,
                   :if => :address_changed?

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :events

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :remember_token
  has_many :apps
  before_save {self.email = email.downcase}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true,
            length: { maximum: 50}

  validates :email, presence: true,
            length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: {case_sensitive: false}

  has_secure_password
  validates :password, presence: true,
            length: { minimum: 6}

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include Knock::Authenticable
  before_action :no_cache

  def no_cache
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 09 Jan 2004 00:00:00 GMT"
  end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController

  APPLICATION_CREATED = "Application created"
  APPLICATION_DELETED = "Application deleted"
  def new
    @app = App.new
  end

  def create
    @app = currentdev_user.apps.build(app_params)
    if @app.save
      flash[:success] = APPLICATION_CREATED
      redirect_to currentdev_user
    else
      render 'new'
    end
  end

  def destroy
    App.find(params[:id]).destroy
    flash[:success] = APPLICATION_DELETED
    redirect_to currentdev_user
  end

  private
  def app_params
    params.require(:app).permit(:name, :apikey)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = currentdev_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  INVALID_LOGIN = "Invaild login information"
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to home_path
    else
      flash[:danger] = INVALID_LOGIN
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_action :check_if_correct_user, only: [:show, :edit, :update]

  WELCOME_TEXT = "Välkommen"

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    if @user.admin?
      @apps = App.all
    else
      @apps = @user.apps
    end
  end

  def create
    @user = User.new(user_params)
    redirect_to root_path unless @user == currentdev_user
    if @user.save
      log_in @user
      flash[:success] = WELCOME_TEXT
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/api/v1/api_helper.rb
module Api::V1::ApiHelper
end

app/helpers/api/v1/creators_helper.rb
module Api::V1::CreatorsHelper
end

app/helpers/api/v1/events_helper.rb
module Api::V1::EventsHelper
end

app/helpers/api/v1/tags_helper.rb
module Api::V1::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end


  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def currentdev_user
    if (user_id = session[:user_id])
    @currentdev_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @currentdev_user
      end
    end
  end

  def check_if_correct_user

   redirect_to root_path unless @user == currentdev_user
  end

  def logged_in?
    !currentdev_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(currentdev_user)
    session.delete(:user_id)
    @currentdev_user = nil
  end

  def admin?
    currentdev_user.admin?
  end

  def check_if_admin
    unless logged_in?
      redirect_to login_path
    else
      unless currentdev_user.admin?
        redirect_to currentdev_user
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/apps/_app_form.html.erb
<%= form_for(@app) do |f| %>
    <div class="form-group">
      <%= render 'shared/error_messages', obj: f.object %>
      <%= render 'shared/flash_messages' %>
      <%= f.label :name, "Application name" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <%= f.submit "Create application", class: "btn btn-primary" %>

    <%= link_to "Back", home_path, class: "btn btn-primary" %>
<% end %>

app/views/apps/new.html.erb
<%= render 'app_form' %>

app/views/layouts/_header.html.erb
<header class="dropdown-header">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <li><%= link_to "Home", home_path, :class => 'btn btn-primary-outline' %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", currentdev_user, :class => 'btn btn-primary-outline' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete", :class => 'btn btn-primary-outline' %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Sign in", login_path, :class => 'btn btn-primary-outline' %></li>
            <li><%= link_to "Sign up", new_user_path, :class => 'btn btn-primary-outline' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RegistrationApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if obj && obj.errors.any? %>
  <div class="alert alert-danger">
    <% obj.errors.full_messages.each do |error_msg| %>
      <p><%= error_msg %></p>
    <% end %>
  </div>
<% end %>

app/views/shared/_flash_messages.erb
<% flash.each do |message_type, message| %>
  <!-- The HTML class will be for instance "flash-success" or "flash-notice" -->
  <div class="alert alert-success">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <p class="notice"> <%= message %> </p>
  </div>
  <p class="alert"> <%= alert %> </p>
<% end %>